import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <header>{/* <HeaderVideo /> */}</header>
      <h1>Welcome to Home pages</h1>
    </div>
  );
};

export default page;
